## Python 리스트를 Numpy 배열로 변환

In [2]:
import numpy as np

list_python = [1, 2, 3, 4] # 파이썬 리스트 생성
numpy_arr = np.array(list_python) # 파이썬 리스트를  numpy 배열로 변환
numpy_arr

array([1, 2, 3, 4])

## Numpy에서 제공하는 함수를 통해 Numpy 배열 생성

In [4]:
zero_arr = np.zeros((2, 2)) # 전부 0으로 채워진 (2, 2) 배열 생성
onae_arr = np.ones((2, 3)) # 전부 1으로 채워진 (2, 3) 배열 생성
five_arr = np.full((2, 3), 5) # 전부 5으로 채워진 (2, 3) 배열 생성
identity_arr = np.eye(3) # (3, 3) 배열 생성

identity_arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 배열 슬라이싱

In [ ]:
p_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr = np.array(p_list) # Python 리스트로부터 (3, 3) 배열 생성

ex1 = arr[0:2, 0:2] # row 와 column 이 0~1까지인 원소들만 선택
print(ex1)

ex2 = arr[1:, 1:] # row 와 column 이 1~끝까지인 원소들만 선택
print(ex2)

ex3 = arr[-1, 0:] # row가 마지막이고 column이 0~끝까지인 원소들만 선택
print(ex3)

[[1 2]
 [4 5]]
[[5 6]
 [8 9]]
[7 8 9]


## 자신이 원하는 원소들을 Index

In [ ]:
target_arr = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8]) # 선택하고 싶은 Index들을 np.array 형태에 저장
print(target_arr[idx]) # [11 33 55 77 99]

[11 33 55 77 99]


## Boolean 값으로 인덱싱하기

In [ ]:
target_arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
bool_idx = (target_arr % 2  == 0) # 2로 나누어 떨어지는 boolean 값으로 저정
print(bool_idx)
print(target_arr[bool_idx]) # [0 2 4 6 8]

[ True False  True False  True False  True False  True False]
[0 2 4 6 8]


In [ ]:
target_arr[target_arr % 2 == 0]

array([0, 2, 4, 6, 8])

## 배열 크기 확인

In [ ]:
a = np.array([1, 2, 3])
print(a.shape) # (3, ) 1차원 배열: vector

a = np.array([[1], [2], [3]])
print(a.shape) # (3, 1) 2차원 배열: 행렬, matrix

b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.shape) # (2, 3)

(3,)
(3, 1)
(2, 3)


## 배열 자료형 확인

In [ ]:
a = np.array([1, 2, 3])
print(a.dtype) # int64

b = np.array([1, 2, 3.])
print(b.dtype) # float64

int64
float64


## 크기가 서로 동일할 때 연산 가능

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b # 각 원소끼리 더하기
print(c)

c = a - b # 각 원소끼리 빼기
print(c)

c = a * b # 각 원소끼리 곱하기
print(c)

c = a / b # 각 원소끼리 나누기
print(c)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


## 브로드캐스트라는 기능을 통해, 연산 가능

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)

b = np.array([10, 11, 12])
print(b.shape)

(2, 3)
(3,)


In [ ]:
print(a + b) # [[11 13 15] [14 16 18]]
print(a * b) # [[10 22 36] [40 55 72]]
print(a * 10) # [[10 20 30] [40 50 60]]
print(a ** 2) # [[ 1  4  9] [16 25 36]]

[[11 13 15]
 [14 16 18]]
[[10 22 36]
 [40 55 72]]
[[10 20 30]
 [40 50 60]]
[[ 1  4  9]
 [16 25 36]]


## 정렬 관련 함수들

In [5]:
a = np.array([2, 5, 3, 6, 8, 1])

b = np.sort(a) # 전체 성분에 대해서 오름차순으로 정렬
print(b)

c = np.sort(a)[::-1] # 전체 성분에 대해서 내림차순으로 정렬
print(c)

d = np.argsort(a) # 오름차순으로 인덱스를 반환
print(d)

[1 2 3 5 6 8]
[8 6 5 3 2 1]
[5 0 2 1 3 4]


## 난수 생성

In [ ]:
a = np.random.rand(5)
print(a)

b = np.random.rand(2, 3)
print(b)

[0.58195863 0.79075914 0.64720425 0.5295949  0.42630249]
[[0.89715741 0.99725208 0.18573823]
 [0.05326519 0.70364324 0.5832836 ]]
