<a href="https://colab.research.google.com/github/gaegulbox/CNU_AI/blob/main/Practice02_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch

In [ ]:
import torch # PyTorch를 Import합니다.

x = torch.Tensor([23, 22, 11, 33])
x

tensor([23., 22., 11., 33.])

In [ ]:
x.size()

torch.Size([4])

In [ ]:
x = torch.FloatTensor([23, 24, 25.5, 26, 27.2])
x

tensor([23.0000, 24.0000, 25.5000, 26.0000, 27.2000])

In [ ]:
x = torch.zeros(5, 3)
print(x)
print(x.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.Size([5, 3])


In [ ]:
import gdown
import numpy as np
import torch
from PIL import Image
import os

# 이미지 다운로드
file_id = "1QkT2-WFoQ-WLn4dGmSWfuhaDajDPrCZd"

# 저장할 폴더 및 파일 경로
save_dir = "./images"
os.makedirs(save_dir, exist_ok=True)
save_path = os.path.join(save_dir, "image.jpg")
gdown.download(id=file_id, output=save_path, quiet=False)

image = Image.open(save_path)

# Numpy 배열로 변환
np_image = np.array(image)

# Tensor로 변환
tensor = torch.from_numpy(np_image)
print("Tensor Shape:", tensor.shape)


Downloading...
From: https://drive.google.com/uc?id=1QkT2-WFoQ-WLn4dGmSWfuhaDajDPrCZd
To: /content/images/image.jpg
100%|██████████| 321k/321k [00:00<00:00, 5.24MB/s]

Tensor Shape: torch.Size([407, 723, 3])


In [ ]:
a = torch.rand(1000, 100000)
b = torch.rand(1000, 100000)

# GPU가 사용가능한지 확인
if torch.cuda.is_available():
    # cuda() 함수를 통해 gpu tensor로 변환
    a = a.cuda()
    b = b.cuda()

print(a)
print(b)

tensor([[0.4446, 0.3421, 0.3882,  ..., 0.0308, 0.5969, 0.2718],
        [0.8839, 0.9223, 0.0017,  ..., 0.4108, 0.4713, 0.2970],
        [0.1855, 0.4101, 0.5161,  ..., 0.8641, 0.0764, 0.5803],
        ...,
        [0.1849, 0.3430, 0.9473,  ..., 0.9789, 0.3294, 0.1368],
        [0.5327, 0.3971, 0.3249,  ..., 0.0983, 0.4922, 0.5944],
        [0.7459, 0.0596, 0.1581,  ..., 0.7629, 0.9351, 0.8104]],
       device='cuda:0')
tensor([[0.5351, 0.2343, 0.5765,  ..., 0.0924, 0.4850, 0.9942],
        [0.3460, 0.9927, 0.6643,  ..., 0.1552, 0.1144, 0.8048],
        [0.9182, 0.2182, 0.3990,  ..., 0.7856, 0.6300, 0.1211],
        ...,
        [0.1506, 0.9444, 0.0334,  ..., 0.7498, 0.1217, 0.1269],
        [0.1623, 0.1361, 0.5037,  ..., 0.8382, 0.3532, 0.0248],
        [0.4517, 0.7265, 0.4717,  ..., 0.8934, 0.9736, 0.0598]],
       device='cuda:0')


# 텐서 다루기

In [ ]:
tensor = torch.FloatTensor([[1., 2., 3.],
                           [4, 5, 6],
                           [7, 8, 9],
                           [10, 11, 12]
                           ])
tensor

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [ ]:
tensor.dim() # tensor의 차원 확인

2

In [ ]:
tensor.size() # tensor의 shape 확인

torch.Size([4, 3])

In [ ]:
tensor[:, 1] # 2번째 열만 취함

tensor([ 2.,  5.,  8., 11.])

In [ ]:
tensor[:, 1].size() # shape 확인

torch.Size([4])

In [ ]:
t1 = torch.Tensor([[3, 3]])
t2 = torch.Tensor([[2, 1]])

t1 + t2

tensor([[5., 4.]])

In [ ]:
# Vector + scalar
t1 = torch.Tensor([[1, 2]])
t2 = torch.Tensor([3]) # [3] -> [3, 3]

t1 + t2

tensor([[4., 5.]])

In [ ]:
# 1 x 2 Vector + 2 x 1 Vector --> 수학적으로는 연산 불가능
t1 = torch.Tensor([[1, 2]]) # (1 x 2) -> (2 x 2)
t2 = torch.Tensor([[3], [4]]) # (2 x 1) -> (2 x 2)

t1 + t2

tensor([[4., 5.],
        [5., 6.]])

In [ ]:
t1 = torch.FloatTensor([[1, 2], [3, 4]])
t2 = torch.FloatTensor([[1], [2]])

print(t1)
print(t2)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1.],
        [2.]])


In [ ]:
t1.matmul(t2) # 행렬 곱셈

tensor([[ 5.],
        [11.]])

In [ ]:
t1 @ t2 # 행렬 곱셈

tensor([[ 5.],
        [11.]])

In [ ]:
t1 * t2 # 행렬의 원소별 곱셈

tensor([[1., 2.],
        [6., 8.]])

In [ ]:
t1.mul(t2) # 행렬의 원소별 곱셈

tensor([[1., 2.],
        [6., 8.]])

In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])
t

tensor([[1., 2.],
        [3., 4.]])

In [ ]:
print(t.sum()) # 단순히 원소 전체의 덧셈을 수행
print(t.sum(dim=0)) # 행을 제거하면서 뎃셈 수행
print(t.sum(dim=1)) # 열을 제거하면서 덧셈 수행
print(t.sum(dim=-1)) # 마지막 차원을 제거하면서 덧셈 수행 --> 열 제거

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [ ]:
print(t.mean()) # 단순히 원소 전체의 평균을 계산
print(t.mean(dim=0)) # 행을 제거하면서 평균 계산
print(t.mean(dim=1)) # 열을 제거하면서평균 계산
print(t.mean(dim=-1)) # 마지막 차원을 제거하면서 평균 계산 --> 열 제거

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [ ]:
print(t.max()) # 단순히 원소 전체의 최대값 반환
print(t.max(dim=0)) # 행을 제거하면서 최대값 반환
print(t.max(dim=1)) # 열을 제거하면서 최대값 반환
print(t.max(dim=-1)) # 마지막 차원을 제거하면서 최대값 반환 --> 열 제거

tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


In [ ]:
print(t.argmax()) # 단순히 원소 전체의 최대값의 인덱스 반환
print(t.argmax(dim=0)) # 행을 제거하면서 최대값의 인덱스 반환
print(t.argmax(dim=1)) # 열을 제거하면서 최대값의 인덱스 반환
print(t.argmax(dim=-1)) # 마지막 차원을 제거하면서 최대값의 인덱스 반환 --> 열 제거

tensor(3)
tensor([1, 1])
tensor([1, 1])
tensor([1, 1])


# 뷰(View)

In [ ]:
tensor = torch.FloatTensor([[[0, 1, 2],
                           [3, 4, 5]],
                           [[6, 7, 8],
                           [9, 10, 11]]])
tensor

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])

In [ ]:
tensor.shape

torch.Size([2, 2, 3])

In [ ]:
viewed_tensor = tensor.view([-1, 3])
viewed_tensor.shape

torch.Size([4, 3])

In [ ]:
viewed_tensor2 = tensor.view([-1, 1, 3])
viewed_tensor2.shape

torch.Size([4, 1, 3])

# 스퀴즈(Squeeze)

In [ ]:
tensor = torch.FloatTensor([[0], [1], [2]])
tensor

tensor([[0.],
        [1.],
        [2.]])

In [ ]:
tensor.shape

torch.Size([3, 1])

In [ ]:
squeezed_tensor = tensor.squeeze()
squeezed_tensor

tensor([0., 1., 2.])

In [ ]:
squeezed_tensor.shape

torch.Size([3])

# 언스퀴즈(Unsqueeze)

In [ ]:
tensor = torch.FloatTensor([0, 1, 2])
tensor.shape

torch.Size([3])

In [ ]:
unsqueezed_tensor = tensor.unsqueeze(0)
unsqueezed_tensor.shape

torch.Size([1, 3])

In [ ]:
unsqueezed_tensor

tensor([[0., 1., 2.]])

# 타입 캐스팅(Type Casting)

In [ ]:
long_tensor = torch.LongTensor([1, 2, 3, 4])
long_tensor

tensor([1, 2, 3, 4])

In [ ]:
long_tensor.type()

'torch.LongTensor'

In [ ]:
float_tensor = long_tensor.float()
float_tensor

tensor([1., 2., 3., 4.])

In [ ]:
float_tensor.type()

'torch.FloatTensor'

# Concatenate

In [ ]:
x = torch.Tensor([[1, 2], [3, 4]])
y = torch.Tensor([[5, 6], [7, 8]])

In [ ]:
concat_tensor1 = torch.cat([x, y], dim=0)
concat_tensor1

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [ ]:
concat_tensor1.shape

torch.Size([4, 2])

In [ ]:
concat_tensor2 = torch.cat([x, y], dim=1)
concat_tensor2

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])

In [ ]:
concat_tensor2.shape

torch.Size([2, 4])

# Stacking

In [ ]:
x = torch.Tensor([1, 4])
y = torch.Tensor([2, 5])
z = torch.Tensor([3, 6])

In [ ]:
stacked_tensor1 = torch.stack([x, y, z])
stacked_tensor1

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [ ]:
stacked_tensor1.shape

torch.Size([3, 2])

In [ ]:
stacked_tensor2 = torch.stack([x, y, z], dim=1)
stacked_tensor2

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
stacked_tensor2.shape

torch.Size([2, 3])